CREATE TABLE notes
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    note       TEXT,
    mood       VARCHAR(255),
    pokemon_id INTEGER,
    CONSTRAINT pk_notes PRIMARY KEY (id)
);

ALTER TABLE notes
    ADD CONSTRAINT uc_notes_pokemon UNIQUE (pokemon_id);

ALTER TABLE notes
    ADD CONSTRAINT FK_NOTES_ON_POKEMON FOREIGN KEY (pokemon_id) REFERENCES pokemonchiki (id);